name: Matrix QC Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  run_matrix:
    name: ${{ matrix.method }} | ${{
      matrix.detector }} | ${{
      matrix.matcher }} | ${{
      matrix.homography }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 20   # حداکثر موازی ممکن (GitHub معمولاً تا 20 اجازه می‌دهد)
      matrix:
        method: [method1, method2, method3]
        detector: [sift, orb, akaze, brisk]
        matcher: [bf, flann]
        homography: [ransac, lmeds, usac, lstsq, dlt]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          echo ">>> Running ${{ matrix.method }} with ${{ matrix.detector }} / ${{ matrix.matcher }} / ${{ matrix.homography }}"
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python src/pipelines/${{ matrix.method }}_pipeline.py \
            --detector_name ${{ matrix.detector }} \
            --matcher_name ${{ matrix.matcher }} \
            --homography_name ${{ matrix.homography }} \
            --n_baseline 40
        env:
          PYTHONUNBUFFERED: 1

      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.method }}-${{ matrix.detector }}-${{ matrix.matcher }}-${{ matrix.homography }}
          path: results/
