name: fault Detection Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run orchestrator
        run: |
          python -m src.orchestrator.orchestrator --grid configs/grid_full.yaml

          
      - name: Debug workspace content
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Files and folders ==="
          ls -R .

      - name: Upload results (if exist)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
          name: results
          path: results/
